# Grunt aliases
---

#updates all grunt dependencies (including foundation)
update:
  - 'devUpdate:main'
  - 'bower:install'
  - 'copy:update'

cleaner:
  - 'clean'
#Backup things
backup:
  - 'copy:backup'


# Build everything
build:
  - 'build:assets'
  - 'assemble'
# Build assets
'build:assets':
  - 'modernizr'
  - 'copy:dist'
  - 'concat:foundation'
  - 'babel:foundation'
  - 'uglify'
  - 'sass'
  - 'postcss:all'  

# Minify (not used yet!)
minify:
  - 'uglify'
  - 'postcss:nano'

# Deploy
deploy:
  - 'build:assets'
  - 'minify'
  - 'copy:deploy'


# Server
server:
  - 'connect:server:keepalive'

# Default
default:
  - 'build'
  - 'watch'