# Grunt aliases
---

#Initialise repositories
initialise:
  - 'bower:install'
cleaner:
  - 'clean'
#Backup things
backup:
  - 'copy:backup'
# Build everything
build:
  - 'build:assets'
  - 'assemble'
# Build assets
'build:assets':
  - 'copy:dist'
  - 'sass'
  - 'concat'
  - 'uglify'
  - 'string-replace'

# Deploy
deploy:
  - 'build'
  - 'cssmin'

# Server
server:
  - 'connect:server:keepalive'

# Default
default:
  - 'build'
  - 'watch'