# Grunt aliases
---

#Initialise repositories
initialize:
  - 'devUpdate:main'
  - 'bower:install'
  - 'copy:local'

#updates all grunt dependencies (including foundation)
update:
  - 'devUpdate:main'
  - 'bower:install'
  - 'copy:update'

cleaner:
  - 'clean'
#Backup things
backup:
  - 'copy:backup'
# Build everything
build:
  - 'build:assets'
  - 'assemble'
# Build assets
'build:assets':
  - 'modernizr'
  - 'copy:dist'
  - 'concat:foundation'
  - 'babel:foundation'
  - 'uglify'
  - 'compass'
  - 'postcss'  

# Deploy
deploy:
  - 'build:assets'
  - 'copy:deploy'
  

# Server
server:
  - 'connect:server:keepalive'

# Default
default:
  - 'build'
  - 'watch'