# Grunt aliases
---

#updates all grunt dependencies (including foundation)
update:
  - 'devUpdate:main'

cleaner:
  - 'clean'
#Backup things
backup:
  - 'copy:backup'


# Build everything
build:
  - 'build:assets'
  - 'assemble'
# Build assets
'build:assets':
  - 'modernizr'
  - 'copy:dist'
  - 'concat:foundation'
  - 'babel:foundation'
  - 'concat:all'
  - 'sass'
  - 'postcss:all'

# Deploy
deploy:
  - 'imagemin'
  - 'postcss:deploy'
  - 'copy:deploy'
  - 'uglify'
# prettify copies also pages, not needed now :)
#  - 'prettify'

# Server
server:
  - 'connect:server:keepalive'

# Default
default:
  - 'build'
  - 'watch'